// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEETEK_EMS_DB;

#nullable disable

namespace SEETEK_EMS_DB.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SEETEK_EMS_DB.Models.Operation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.ProductionOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Partnumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoutingMapID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("RoutingMapID");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.ResourceGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.ToTable("ResourceGroups");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.RoutingMap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OperationID")
                        .HasColumnType("int");

                    b.Property<int>("ResourceGroupID")
                        .HasColumnType("int");

                    b.Property<int>("StationID")
                        .HasColumnType("int");

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("OperationID");

                    b.HasIndex("ResourceGroupID");

                    b.HasIndex("StationID");

                    b.ToTable("RoutingMaps");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.SN", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductionOrderID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("ProductionOrderID");

                    b.ToTable("SNs");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.SNTracking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("RoutingMapID")
                        .HasColumnType("int");

                    b.Property<int>("RoutingMapStep")
                        .HasColumnType("int");

                    b.Property<int>("SNID")
                        .HasColumnType("int");

                    b.Property<string>("SNName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("RoutingMapID");

                    b.HasIndex("SNID");

                    b.ToTable("SNTrackings");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.Station", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.ProductionOrder", b =>
                {
                    b.HasOne("SEETEK_EMS_DB.Models.RoutingMap", "RoutingMap")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("RoutingMapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoutingMap");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.RoutingMap", b =>
                {
                    b.HasOne("SEETEK_EMS_DB.Models.Operation", "Operation")
                        .WithMany("RoutingMaps")
                        .HasForeignKey("OperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEETEK_EMS_DB.Models.ResourceGroup", "ResourceGroup")
                        .WithMany("RoutingMaps")
                        .HasForeignKey("ResourceGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEETEK_EMS_DB.Models.Station", "Station")
                        .WithMany("RoutingMaps")
                        .HasForeignKey("StationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("ResourceGroup");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.SN", b =>
                {
                    b.HasOne("SEETEK_EMS_DB.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("SNs")
                        .HasForeignKey("ProductionOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.SNTracking", b =>
                {
                    b.HasOne("SEETEK_EMS_DB.Models.RoutingMap", "RoutingMap")
                        .WithMany()
                        .HasForeignKey("RoutingMapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEETEK_EMS_DB.Models.SN", "SN")
                        .WithMany()
                        .HasForeignKey("SNID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RoutingMap");

                    b.Navigation("SN");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.Operation", b =>
                {
                    b.Navigation("RoutingMaps");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.ProductionOrder", b =>
                {
                    b.Navigation("SNs");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.ResourceGroup", b =>
                {
                    b.Navigation("RoutingMaps");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.RoutingMap", b =>
                {
                    b.Navigation("ProductionOrders");
                });

            modelBuilder.Entity("SEETEK_EMS_DB.Models.Station", b =>
                {
                    b.Navigation("RoutingMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
